### PR TITLE
Added Hungarian translation.

### PR DESCRIPTION
**Pull request by martonmiklos**
Hey Slava,

Many thanks for creating this plugin. 
I hope you will get this upstreamed into the SFOS soon.
In the meantime I have created a Hungarian translation for it.

### CODE REVIEW

**Comment by monich** [comment]
Thanks!

**Comment by monich** [comment]
I have replaced _Ébresztő beállításai_ with _Óra_ so that it matches the icon label

**Comment by martonmiklos** [comment]
Well I did that with intention, but as you have mentioned I might be wrong. 

"Ébresztő beállításai" means "Alarm clock settings" in English. However if I think right the snooze time of the calendar alarms are using the same duration.

Also adding the "settings" suffix would also break the consistency (no other settings pages specifying it).

**Comment by monich** [comment]
It was about consistency, rather than grammatical correctness. The norm is to have settings page header matching the icon label, I just followed that pattern.

**Pull request merged**
